# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_position_limits: true     # 添加位置限位
    min_position: -1.57         # 最小角度 -180°
    max_position: 1.57          # 最大角度 180°
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.2
  joint_2:
    has_position_limits: true     # 添加位置限位
    min_position: -1.57          # 最小角度 -180°
    max_position: 1.57          # 最大角度 180°
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.2
  joint_3:
    has_position_limits: true     # 添加位置限位
    min_position: -2.00       # 最小角度 -180°
    max_position: 2.00          # 最大角度 180°
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.2
  joint_4:
    has_position_limits: true     # 添加位置限位
    min_position: -2.00         # 最小角度 -180°
    max_position: 2.00            # 最大角度 180°
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.2
  joint_5:
    has_position_limits: true     # 添加位置限位
    min_position: -1.57          # 最小角度 -180°
    max_position: 1.57         # 最大角度 180°
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.2
  joint_6:
    has_position_limits: true     # 添加位置限位
    min_position: -2.00         # 最小角度 -180°
    max_position: 2.00            # 最大角度 180°
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.2