# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.75
    has_acceleration_limits: true
    max_acceleration: 0.7
    has_jerk_limits: false
 
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.71
    has_acceleration_limits: true
    max_acceleration: 0.7
    has_jerk_limits: false
   
  joint_3:
    has_velocity_limits: true
    max_velocity: 2.71
    has_acceleration_limits: true
    max_acceleration: 0.7
    has_jerk_limits: false
    
  joint_4:
    has_velocity_limits: true
    max_velocity: 3.54
    has_acceleration_limits: true
    max_acceleration: 0.7
    has_jerk_limits: false
    
  joint_5:
    has_velocity_limits: true
    max_velocity: 32.609999999999999
    has_acceleration_limits: true
    max_acceleration: 0.7
    has_jerk_limits: false
    
  joint_6:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true
    max_acceleration: 0.7
    has_jerk_limits: false
    