rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::controller::communication::InputTest -> input
      - rmcs_core::controller::communication::OutputTest -> output
      - rmcs_core::broadcaster::ValueBroadcaster -> broadcaster

input:
  ros__parameters:
    name_sin: /communication/value_sin
    name_cos: /communication/value_cos
    name_sum: /communication/value_sum
output:
  ros__parameters:
    name_sin: /communication/value_sin
    name_cos: /communication/value_cos
    w: 6.283185307179586  # 0.2 * pi

broadcaster:
  ros__parameters:
    forward_list:
      - /communication/value_sin
      - /communication/value_cos
      - /communication/value_sum