rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::CatapultDart -> dart_hardware
      - rmcs_core::controller::dart::DartLaunchController -> launch_controller


dart_hardware:
  ros__parameters:
    usb_pid: -1

launch_controller:
  ros__parameters:
    belt_velocity: 10.0
    sync_coefficient: 0.5
    b_kp: 1.0
    b_ki: 0.0
    b_kd: 0.0