rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::CatapultDart -> dart_hardware
      - rmcs_core::controller::dart::DartLaunchController -> launch_controller
      # - rmcs_core::hardware::ServoTest -> servo_test
      - rmcs_core::controller::dart::DartSettings -> dart_settings
      - rmcs_core::broadcaster::ValueBroadcaster -> broadcaster

broadcaster:
  ros__parameters:
    forward_list:
      - /dart/force_control_motor/control_velocity
      - /dart/drive_belt/left/control_torque
      - /dart/drive_belt/left/velocity
      - /dart/drive_belt/right/control_torque
      - /dart/drive_belt/right/velocity
      - /dart/force_control_motor/velocity

dart_hardware:
  ros__parameters:
    usb_pid: -1

launch_controller:
  ros__parameters:
    belt_velocity: 10.0
    sync_coefficient: 0.5
    b_kp: 1.0
    b_ki: 0.0
    b_kd: 0.0
    max_control_torque: 1.0
    trigger_free_angle: 0x0E2A
    trigger_lock_angle: 0x0FC1

servo_test:
  ros__parameters:
    trigger_free_angle: 0x0E2A
    trigger_lock_angle: 0x0FC1

dart_settings:
  ros__parameters:
    log_enable: false
    screw_max_velocity: 10.0