rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Arm -> arm_hardware
      - rmcs_core::controller::arm::ArmController -> arm_controller
      - rmcs_core::controller::arm::ArmConfig -> arm_config
      - rmcs_core::controller::arm::ArmMoveitProcess -> arm_moveit_process

      - rmcs_core::controller::pid::ErrorPidController -> joint5_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> joint5_velocity_pid_controller

      - rmcs_core::controller::pid::ErrorPidController -> joint4_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> joint4_velocity_pid_controller

      - rmcs_core::controller::pid::ErrorPidController -> joint3_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> joint3_velocity_pid_controller

      - rmcs_core::controller::pid::ErrorPidController -> joint2_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> joint2_velocity_pid_controller

      - rmcs_core::controller::pid::ErrorPidController -> joint1_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> joint1_velocity_pid_controller

      - rmcs_core::controller::arm::ArmSolver -> arm_solver
      - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster
arm_hardware:
  ros__parameters:
    arm_board_usb_pid: 0x488d
    joint5_zero_point: 6735
    joint4_zero_point: 10365
    joint3_zero_point: 40955
    joint2_zero_point: 38788 
    joint1_zero_point: 48020 

arm_config:
  ros__parameters: {}

arm_solver:
  ros__parameters:
    controller_list: [gravity, friction]

arm_controller:
  ros__parameters: {}

joint5_angle_pid_controller:
  ros__parameters:
    measurement: /arm/joint_5/control_angle_error
    control: /arm/joint_5/control_velocity
    kp: 20.0
    ki: 0.0
    kd: 2.0

joint5_velocity_pid_controller:
  ros__parameters:
    measurement: /arm/joint_5/velocity
    setpoint: /arm/joint_5/control_velocity
    control: /arm/joint_5/control_torque
    kp: 0.028
    ki: 0.0
    kd: 0.0009

joint4_angle_pid_controller:
  ros__parameters:
    measurement: /arm/joint_4/control_angle_error
    control: /arm/joint_4/control_velocity
    kp: 20.0
    ki: 0.0
    kd: 2.0
joint4_velocity_pid_controller:
  ros__parameters:
    measurement: /arm/joint_4/velocity
    setpoint: /arm/joint_4/control_velocity
    control: /arm/joint_4/control_torque
    kp: 0.06
    ki: 0.0
    kd: 0.001

joint3_angle_pid_controller:
  ros__parameters:
    measurement: /arm/joint_3/control_angle_error
    control: /arm/joint_3/control_velocity
    kp: 20.0
    ki: 0.0
    kd: 2.0
joint3_velocity_pid_controller:
  ros__parameters:
    measurement: /arm/joint_3/velocity
    setpoint: /arm/joint_3/control_velocity
    control: /arm/joint_3/control_torque
    kp: 0.005
    ki: 0.0
    kd: 0.002

joint2_angle_pid_controller:
  ros__parameters:
    measurement: /arm/joint_2/control_angle_error
    control: /arm/joint_2/control_velocity
    kp: 20.0
    ki: 0.0
    kd: 2.0
joint2_velocity_pid_controller:
  ros__parameters:
    measurement: /arm/joint_2/velocity
    setpoint: /arm/joint_2/control_velocity
    control: /arm/joint_2/control_torque
    kp: 0.0025
    ki: 0.0
    kd: 0.0004

joint1_angle_pid_controller:
  ros__parameters:
    measurement: /arm/joint_1/control_angle_error
    control: /arm/joint_1/control_velocity
    kp: 20.0
    ki: 0.0
    kd: 2.0
joint1_velocity_pid_controller:
  ros__parameters:
    measurement: /arm/joint_1/velocity
    setpoint: /arm/joint_1/control_velocity
    control: /arm/joint_1/control_torque
    kp: 0.042
    ki: 0.0
    kd: 0.0001


value_broadcaster:
  ros__parameters:
    forward_list:
      - "/arm/joint_5/motor/control_torque"

