rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Engineer -> engineer_hardware
      - rmcs_core::controller::arm::ArmController -> arm_controller

      - rmcs_core::controller::leg::LegController -> leg_controller
      - rmcs_core::controller::chassis::Chassis_Controller -> chassis_controller
      - rmcs_core::controller::chassis::SteeringWheelController -> steering_wheel_controller
            
      - rmcs_core::controller::pid::ErrorPidController -> joint6_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> joint6_velocity_pid_controller

      - rmcs_core::controller::pid::ErrorPidController -> joint5_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> joint5_velocity_pid_controller

      - rmcs_core::controller::pid::ErrorPidController -> joint4_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> joint4_velocity_pid_controller

      - rmcs_core::controller::pid::ErrorPidController -> joint3_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> joint3_velocity_pid_controller

      - rmcs_core::controller::pid::ErrorPidController -> joint2_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> joint2_velocity_pid_controller

      - rmcs_core::controller::pid::ErrorPidController -> joint1_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> joint1_velocity_pid_controller

      - rmcs_core::controller::pid::PidController -> leg_omni_l_velocity_controller
      - rmcs_core::controller::pid::PidController -> leg_omni_r_velocity_controller

      - rmcs_core::controller::pid::ErrorPidController -> big_yaw_angle_error_pid_controller
      - rmcs_core::controller::pid::PidController -> big_yaw_velocity_pid_controller

      - rmcs_core::controller::pid::ErrorPidController -> leg_lf_angle_error_pid_controller
      - rmcs_core::controller::pid::PidController -> leg_lf_velocity_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> leg_rf_angle_error_pid_controller
      - rmcs_core::controller::pid::PidController -> leg_rf_velocity_pid_controller

      - rmcs_core::controller::pid::ErrorPidController -> leg_lb_angle_error_pid_controller
      - rmcs_core::controller::pid::PidController -> leg_lb_velocity_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> leg_rb_angle_error_pid_controller
      - rmcs_core::controller::pid::PidController -> leg_rb_velocity_pid_controller

      - rmcs_core::controller::pid::PidController -> arm_pump_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> mine_pump_velocity_pid_controller
      - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster
engineer_hardware:
  ros__parameters:
    arm_board_usb_pid: 0x1783
    left_board_usb_pid: 0x652f
    right_board_usb_pid: 0x75f3
    joint6_zero_point: 0
    joint5_zero_point: 37361
    joint4_zero_point: 12200
    joint3_zero_point: 260992
    joint2_zero_point: 52343 
    joint6_qlim: [-3.141592,3.141592]    
    joint5_qlim: [-1.93532,1.93532]    
    joint4_qlim: [-3.141592,3.141592]    
    joint3_qlim: [-1.0472,0.8727]    
    joint2_qlim: [-1.308,1.16719]    
    steering_lf_zero_point: 1365
    steering_lb_zero_point: 1365
    steering_rb_zero_point: 0
    steering_rf_zero_point: 7444
    leg_lf_ecd_zero_point: 109021
    leg_lb_ecd_zero_point: 153207
    leg_rb_ecd_zero_point: 2135
    leg_rf_ecd_zero_point: 133400
    big_yaw_zero_point: 20485


leg_controller:
  ros__parameters:
    forward_x_position_in_FourWheel: 243.0




joint6_angle_pid_controller:
  ros__parameters:
    measurement: /arm/Joint6/control_angle_error
    control: /arm/Joint6/control_velocity
    kp: 9620.0
    ki: 0.0
    kd: 25.0

joint6_velocity_pid_controller:
  ros__parameters:
    measurement: /arm/Joint6/velocity
    setpoint: /arm/Joint6/control_velocity
    control: /arm/Joint6/control_torque
    kp: 0.021
    ki: 0.0
    kd: 0.0005

joint5_angle_pid_controller:
  ros__parameters:
    measurement: /arm/Joint5/control_angle_error
    control: /arm/Joint5/control_velocity
    kp: 6920.0
    ki: 0.0
    kd: 15.0

joint5_velocity_pid_controller:
  ros__parameters:
    measurement: /arm/Joint5/velocity
    setpoint: /arm/Joint5/control_velocity
    control: /arm/Joint5/control_torque
    kp: 0.028
    ki: 0.0
    kd: 0.0009

joint4_angle_pid_controller:
  ros__parameters:
    measurement: /arm/Joint4/control_angle_error
    control: /arm/Joint4/control_velocity
    kp: 3120.0
    ki: 0.0
    kd: 15.0
joint4_velocity_pid_controller:
  ros__parameters:
    measurement: /arm/Joint4/velocity
    setpoint: /arm/Joint4/control_velocity
    control: /arm/Joint4/control_torque
    kp: 0.06
    ki: 0.0
    kd: 0.001

joint3_angle_pid_controller:
  ros__parameters:
    measurement: /arm/Joint3/control_angle_error
    control: /arm/Joint3/control_velocity
    kp: 4290.0
    ki: 0.0
    kd: 20.0
joint3_velocity_pid_controller:
  ros__parameters:
    measurement: /arm/Joint3/velocity
    setpoint: /arm/Joint3/control_velocity
    control: /arm/Joint3/control_torque
    kp: 0.0025
    ki: 0.0
    kd: 0.0002

joint2_angle_pid_controller:
  ros__parameters:
    measurement: /arm/Joint2/control_angle_error
    control: /arm/Joint2/control_velocity
    kp: 4390.0
    ki: 0.0
    kd: 20.0
joint2_velocity_pid_controller:
  ros__parameters:
    measurement: /arm/Joint2/velocity
    setpoint: /arm/Joint2/control_velocity
    control: /arm/Joint2/control_torque
    kp: 0.00293
    ki: 0.0
    kd: 0.00004

joint1_angle_pid_controller:
  ros__parameters:
    measurement: /arm/Joint1/control_angle_error
    control: /arm/Joint1/control_velocity
    kp: 6520.0
    ki: 0.0
    kd: 40.0
joint1_velocity_pid_controller:
  ros__parameters:
    measurement: /arm/Joint1/velocity
    setpoint: /arm/Joint1/control_velocity
    control: /arm/Joint1/control_torque
    kp: 0.042
    ki: 0.0
    kd: 0.0001

leg_omni_l_velocity_controller:
  ros__parameters:
    measurement: /leg/omni/l/velocity
    setpoint: /leg/omni/l/target_vel
    control: /leg/omni/l/control_torque
    kp: 0.7
    ki: 0.0
    kd: 0.0
leg_omni_r_velocity_controller:
  ros__parameters:
    measurement: /leg/omni/r/velocity
    setpoint: /leg/omni/r/target_vel
    control: /leg/omni/r/control_torque
    kp: 0.7
    ki: 0.0
    kd: 0.0

big_yaw_angle_error_pid_controller:
  ros__parameters:
    measurement: /chassis/big_yaw/target_angle_error
    control: /chassis/big_yaw/control_vel
    kp: 91.3
    ki: 0.0
    kd: 2.6
big_yaw_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/big_yaw/velocity
    setpoint: /chassis/big_yaw/control_vel
    control: /chassis/big_yaw/control_torque
    kp: 3.99
    ki: 0.0
    kd: 0.039


leg_lf_angle_error_pid_controller:
  ros__parameters:
    measurement: /leg/joint/lf/control_theta_error
    control: /leg/joint/lf/control_vel
    kp: 100.0
    ki: 0.0
    kd: 5.0
leg_lf_velocity_pid_controller:
  ros__parameters:
    measurement: /leg/joint/lf/velocity
    setpoint: /leg/joint/lf/control_vel
    control: /leg/joint/lf/control_torque
    kp: 2.0
    ki: 0.0
    kd: 0.2

leg_rf_angle_error_pid_controller:
  ros__parameters:
    measurement: /leg/joint/rf/control_theta_error
    control: /leg/joint/rf/control_vel
    kp: 80.0
    ki: 0.0
    kd: 5.0


leg_rf_velocity_pid_controller:
  ros__parameters:
    measurement: /leg/joint/rf/velocity
    setpoint: /leg/joint/rf/control_vel
    control: /leg/joint/rf/control_torque
    kp: 2.0
    ki: 0.0
    kd: 0.2

leg_lb_angle_error_pid_controller:
  ros__parameters:
    measurement: /leg/joint/lb/control_theta_error
    control: /leg/joint/lb/control_vel
    kp: 6000.0
    ki: 0.0
    kd: 0.0
leg_lb_velocity_pid_controller:
  ros__parameters:
    measurement: /leg/joint/lb/velocity
    setpoint: /leg/joint/lb/control_vel
    control: /leg/joint/lb/control_torque
    kp: 0.03
    ki: 0.0
    kd: 0.0

leg_rb_angle_error_pid_controller:
  ros__parameters:
    measurement: /leg/joint/rb/control_theta_error
    control: /leg/joint/rb/control_vel
    kp: 6000.0
    ki: 0.0
    kd: 0.0
leg_rb_velocity_pid_controller:
  ros__parameters:
    measurement: /leg/joint/rb/velocity
    setpoint: /leg/joint/rb/control_vel
    control: /leg/joint/rb/control_torque
    kp: 0.03
    ki: 0.0
    kd: 0.0

steering_wheel_controller:
  ros__parameters:
    mess: 25.0
    moment_of_inertia: 1.0
    vehicle_radius: 0.3238
    wheel_radius: 0.055
    friction_coefficient: 0.6
    k1: 2.958580e+00
    k2: 3.082190e-03
    no_load_power: 11.37

arm_pump_velocity_pid_controller:
  ros__parameters:
    measurement: /arm/pump/velocity
    setpoint: /arm/pump/target_vel
    control: /arm/pump/control_torque
    kp: 0.001
    ki: 0.0
    kd: 0.0
mine_pump_velocity_pid_controller:
  ros__parameters:
    measurement: /mine/pump/velocity
    setpoint: /mine/pump/target_vel
    control: /mine/pump/control_torque
    kp: 0.001
    ki: 0.0
    kd: 0.0


value_broadcaster:
  ros__parameters:
    forward_list:
      - "/leg/joint/lf/control_torque"
      - "/leg/joint/lb/control_torque"

