rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Arm-> arm_hardware
      - rmcs_core::controller::arm::ArmConfig -> arm_config
      - rmcs_core::controller::arm::ArmSolver -> arm_solver
      - rmcs_core::controller::arm::ArmController -> arm_controller
      - rmcs_core::broadcaster::ValueBroadcaster -> value_

arm_hardware:
  ros__parameters:
    arm_board_usb_pid: 0x1783
    joint6_zero_point: 0
    joint5_zero_point: 37436
    joint4_zero_point: 28029
    joint3_zero_point: 28134
    joint2_zero_point: 29790 
    joint1_zero_point: 52343 

arm_solver:
  ros__parameters:
    controller_list: [pid,gravity,friction]

value_:
  ros__parameters:
    forward_list:
      - "/arm/joint_5/motor/control_torque"