rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::simulator::MotorBackdataBridge -> motor_backdata_bridge
      - rmcs_core::simulator::MotorControlBridge -> motor_control_bridge
      - rmcs_core::rmcs_simulator_bridge::angle_test::ComponentD -> executor
      - rmcs_core::controller::pid::PidController -> pid_inner
      - rmcs_core::controller::pid::PidController -> pid_outer
     

motor_backdata_bridge:
  ros__parameters:
    simulated_motor_angle: /motor/angle
    simulated_motor_velocity: /motor/velocity
    simulated_motor_torque: /motor/troque

motor_control_bridge:
  ros__parameters:
    simulated_motor_control_torque: /motor/control_torque

executor:
  ros__parameters:
    output: /motor/control_angle

pid_outer:
  ros__parameters:
    measurement: /motor/angle
    setpoint: /motor/control_angle
    control: /motor/control_velocity
    kp: 10.0  
    ki: 0.0005     
    kd: 0.00002     
    integral_min: -5.0   
    integral_max: 5.0

pid_inner:
  ros__parameters:
    measurement: /motor/velocity
    setpoint: /motor/control_velocity
    control: /motor/control_torque
    kp: 20.0    
    ki: 0.0005     
    kd: 0.00002    



